import {chromium} from 'playwright';
import {start,go,log,body,SH,errs} from './_lib.mjs';
const {b,p}=await start();
await go(p,'budget');
await p.getByRole('button',{name:'חודש קודם'}).click();await p.waitForTimeout(400);
console.log(await p.evaluate(()=>[...document.querySelectorAll('button')].filter(b=>/חודש|20\d\d|היום|איפוס/.test(b.innerText+b.getAttribute('aria-label'))).map(b=>b.outerHTML.slice(0,200))));
await p.getByRole('button',{name:'חזרה לחודש הנוכחי'}).click();await p.waitForTimeout(500);
console.log(await p.evaluate(()=>[...document.querySelectorAll('button')].find(b=>/20\d\d/.test(b.innerText))?.innerText));
await p.screenshot({path:SH+'month.png'});
await p.getByRole('button',{name:/^חשבון/}).click();
console.log(await p.evaluate(()=>[...document.querySelectorAll('[class*=accountPanel] input')].map(i=>i.type+' '+i.className+' '+i.placeholder+' '+getComputedStyle(i).display)));
const inps=p.locator('[class*=accountPanel] input:not([type=file])');
for(let i=0;i<await inps.count();i++){await inps.nth(i).focus();console.log('focus',await inps.nth(i).evaluate(e=>document.activeElement===e));}
await p.keyboard.press('Escape');
await b.close();
const b2=await chromium.launch();const m=await b2.newPage({viewport:{width:390,height:844}});
m.on('pageerror',e=>errs.push('PE m '+e.message));m.on('console',x=>{if(x.type()==='error')errs.push('CE m '+x.text())});
await go(m,'dashboard');await m.screenshot({path:SH+'m-dash.png'});
console.log('mobile buttons:',await m.evaluate(()=>[...document.querySelectorAll('button')].filter(b=>b.offsetParent).map(b=>(b.getAttribute('aria-label')||b.innerText).trim().slice(0,25)).join('|')));
const macc=m.getByRole('button',{name:/^חשבון/});
console.log('acc visible',await macc.isVisible());await macc.click();await m.waitForTimeout(300);
const mp=m.locator('[class*=accountPanel]').first();console.log('mpanel',await mp.boundingBox());await m.screenshot({path:SH+'m-account.png'});
await m.keyboard.press('Escape');await m.waitForTimeout(200);console.log('closed',await m.locator('[class*=accountPanel]').count()===0);
console.log('ERRS',errs);await b2.close();
